steps:
  # Step 1: Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/chefs-companion-repo/chefs-companion:$SHORT_SHA'
      - '.'

  # Step 2: Push the container image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/chefs-companion-repo/chefs-companion:$SHORT_SHA'

  # Step 3: Create a Cloud Deploy release
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'deploy'
      - 'releases'
      - 'create'
      - 'release-$SHORT_SHA'
      - '--delivery-pipeline=chefs-companion-pipeline'
      - '--region=us-central1'
      - '--images=app-image=us-central1-docker.pkg.dev/$PROJECT_ID/chefs-companion-repo/chefs-companion:$SHORT_SHA'

images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/chefs-companion-repo/chefs-companion:$SHORT_SHA'

options:
  requestedVerifyOption: VERIFIED
  logging: CLOUD_LOGGING_ONLY
