apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: chefs-companion-pipeline
serialPipeline:
  stages:
  - targetId: staging
    profiles: [staging]
    strategy:
      standard:
        analysis:
          duration: 600s
          googleCloud:
            alertPolicyChecks:
            - id: alert-check-5xx-staging
              alertPolicies:
              - projects/mattsanta-new-project/alertPolicies/8399868592310363025
              labels:
                service_name: '${{ render.metadata.cloud_run.service.id }}'
                revision_name: '${{ render.metadata.cloud_run.revision.id }}'
  - targetId: prod
    profiles: [prod]
    strategy:
      standard:
        analysis:
          duration: 600s
          googleCloud:
            alertPolicyChecks:
            - id: alert-check-5xx-prod
              alertPolicies:
              - projects/mattsanta-new-project/alertPolicies/7278701443446218612
              labels:
                service_name: '${{ render.metadata.cloud_run.service.id }}'
                revision_name: '${{ render.metadata.cloud_run.revision.id }}'
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: staging
run:
  location: projects/mattsanta-new-project/locations/us-central1
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: prod
run:
  location: projects/mattsanta-new-project/locations/us-central1
---
apiVersion: deploy.cloud.google.com/v1
kind: Automation
metadata:
  name: chefs-companion-pipeline/auto-rollback-staging
serviceAccount: 360003442539-compute@developer.gserviceaccount.com
selector:
  targets:
  - id: staging
rules:
- repairRolloutRule:
    id: "rollback-on-analysis-failure-staging"
    jobs: ["analysis"]
    repairPhases:
    - rollback: {}
---
apiVersion: deploy.cloud.google.com/v1
kind: Automation
metadata:
  name: chefs-companion-pipeline/auto-promote-to-prod
serviceAccount: 360003442539-compute@developer.gserviceaccount.com
selector:
  targets:
  - id: staging
rules:
- promoteReleaseRule:
    id: "promote-after-staging-passes"
    wait: 1m
    destinationTargetId: "@next"
---
apiVersion: deploy.cloud.google.com/v1
kind: Automation
metadata:
  name: chefs-companion-pipeline/auto-rollback-prod
serviceAccount: 360003442539-compute@developer.gserviceaccount.com
selector:
  targets:
  - id: prod
rules:
- repairRolloutRule:
    id: "rollback-on-analysis-failure-prod"
    jobs: ["analysis"]
    repairPhases:
    - rollback: {}
