apiVersion: skaffold/v4beta7
kind: Config
metadata:
  name: chefs-companion
build:
  artifacts:
    - image: IMAGE_PLACEHOLDER
      docker:
        dockerfile: Dockerfile
manifests:
  rawYaml:
    - k8s/deployment.yaml
    - k8s/service.yaml
deploy:
  cloudDeploy: {}
