apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: chefs-companion
deploy:
  kubectl: {}
manifests:
  rawYaml:
    - k8s/deployment.yaml
    - k8s/service.yaml
profiles:
  - name: chefs-companion-dev
  - name: chefs-companion-prod
